version: '3.5'
services:

 redis-service:
  restart: unless-stopped
  image: redis

 frontend:
  build: ./front

 proxy:
  image: jwilder/nginx-proxy
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
   - /var/run/docker.sock:/tmp/docker.sock:ro 
  ports:
   - 80:80
  depends_on:
   - frontend
   - backend

 backend:
  build: ./back
  environment:
    - REDIS=redis-service
    - DB_USERNAME=user
    - DB_PASSWORD=password
    - DB_NAME=name
    - DB_HOST=db
  depends_on:
   - db

 db:
  image: postgres
  restart: unless-stopped
  environment:
   POSTGRES_PASSWORD: password
   POSTGRES_DB: name
   POSTGRES_USER: user
  container_name: postgres_db



