version: '3.2'
services:

 redis-service:
  restart: unless-stopped
  image: redis

 frontend:
  build: ./front
  ports: 
   - 5000:5000

 backend:
  build: ./back
  environment:
    - REDIS=redis-service
  ports: 
   - 8000:8000



